executor: slurm
jobs: 50

set-resources:
  mapping:
    runtime: 720
    threads: 104
    cpus_per_task: 104
    slurm_partition: 12hours
    slurm_extra: "--constraint=cascadelake --cpu-freq=High-High:Performance"
    mem_mb: 1000000
  generate_chrome_ctgs:
    runtime: 30
    threads: 13
    cpus_per_task: 13
    slurm_partition: 30mins
    slurm_extra: "--cpu-freq=High-High:Performance"
    mem_mb: 125000
  calling:
    runtime: 240
    threads: 52
    cpus_per_task: 52
    slurm_partition: 4hours
    slurm_extra: "--constraint=cascadelake --cpu-freq=High-High:Performance"
    mem_mb: 500000
  merge_chroms:
    runtime: 240
    threads: 52
    cpus_per_task: 52
    slurm_partition: 4hours
    slurm_extra: "--constraint=cascadelake --cpu-freq=High-High:Performance"
    mem_mb: 500000
  gembs_extract:
    runtime: 720
    threads: 52
    cpus_per_task: 52
    slurm_partition: 12hours
    slurm_extra: "--constraint=cascadelake --cpu-freq=High-High:Performance"
    mem_mb: 500000
  extract_signal:
    runtime: 240
    threads: 6
    cpus_per_task: 6
    slurm_partition: 4hours
    slurm_extra: "--constraint=cascadelake --cpu-freq=High-High:Performance"
    mem_mb: 500000
  get_methylc_and_coverage:
    runtime: 240
    threads: 16
    cpus_per_task: 16
    slurm_partition: 4hours
    slurm_extra: "--constraint=cascadelake --cpu-freq=High-High:Performance"
    mem_mb: 500000
  make_bedmethyl_pearson_correlation:
    runtime: 30
    threads: 6
    cpus_per_task: 6
    slurm_partition: 30mins
    slurm_extra: "--cpu-freq=High-High:Performance"
    mem_mb: 62500

use-apptainer: True
apptainer-prefix: workflow/rules/envs
software-deployment-method: apptainer
apptainer-args: -B /zata,/data

use-conda: True
conda-prefix: workflow/rules/envs
software-deployment-method: conda

rerun-incomplete: True
max-jobs-per-timespan: 1/1s
printshellcmds: True
# retries: 1

