$schema: "https://json-schema.org/draft-07/schema#"
description: "WGBS pipeline configuration validation"
type: object
properties:
  reference:
    type: string
    description: "Path to reference genome FASTA file"
    pattern: "\\.(fa|fasta|fa\\.gz|fasta\\.gz)$"
  
  extra_reference:
    type: string
    description: "Path to additional reference sequences (optional)"
    pattern: "\\.(fa|fasta|fa\\.gz|fasta\\.gz)$"
  
  indexed_reference:
    type: string
    description: "Path to pre-built gemBS index tarball (optional)"
    pattern: "\\.tar\\.gz$"
  
  indexed_contig_sizes:
    type: string
    description: "Path to chromosome sizes file (optional)"
    pattern: "\\.contig\\.sizes$"
  
  samples:
    type: string
    description: "Path to sample sheet CSV file"
    pattern: "\\.(csv|tsv)$"
  
  pipeline_type:
    type: string
    enum: ["wgbs", "rrbs"]
    default: "wgbs"
    description: "Analysis type: whole genome or reduced representation"