$schema: 'https://json-schema.org/draft/2020-12/schema'
description: "ENCODE WGBS sample sheet entry validation"
type: object
properties:
  "File accession":
    type: string
    pattern: "^ENCFF[A-Z0-9]{6}$"
    description: "ENCODE file accession identifier"

  "Experiment accession":
    type: string
    pattern: "^ENCSR[A-Z0-9]{6}$"
    description: "ENCODE experiment accession identifier"
  
  "File path":
    type: string
    description: "Local file path or download URL"
    anyOf:
      - pattern: "\\.(fastq|fq)(\\.gz)?$"  # Local file path
      - pattern: "^https?://"              # URL
  
  "Biological replicate(s)":
    type: integer
    minimum: 1
    maximum: 20
    description: "Biological replicate number"
  
  "Technical replicate(s)":
    type: string
    pattern: "^\\d+_\\d+$"
    description: "Technical replicate in format 'bio_tech' (e.g., 1_1)"
  
  "Run type":
    type: string
    enum: ["paired-ended", "single-ended"]
    description: "Sequencing run type"
  
  "Paired end":
    type: integer
    enum: [1, 2]
    description: "Read pair number (1 or 2)"
  
  "Paired with":
    type: string
    pattern: "^ENCFF[A-Z0-9]{6}$"
    description: "Accession of paired read file"
  
  # Optional metadata
  "Biosample term name":
    type: string
    description: "Biosample type or tissue name (optional)"

  "Biosample treatments":
    type: string
    description: "Treatment applied to biosample (optional)"

required:
  - "File accession"
  - "Experiment accession"
  - "File path"
  - "Biological replicate(s)"
  - "Technical replicate(s)"
  - "Run type"
  - "Paired end"