# Pipeline configuration
pipeline_type: "wgbs"
samples: ".test2/metadata.tsv"
project: "TEST"
# indexed_reference: "resources/ENCFF603ORM.tar.gz"
gembs_reference: "resources/GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta.gz"
gembs_reference_basename: "GRCh38_no_alt_analysis_set_GCA_000001405.15"
gembs_base: "results"
gembs_threads: "64"
gembs_jobs: "16"
gembs_benchmark_mode: "False"