executor: slurm
jobs: 128

default-resources:
  mem_mb: 32000
  threads: 32
  cores: 32
  runtime: 720
  slurm_partition: 12hours

set-resources:
  make_conf:
    mem_mb: 4000
    threads: 4
    cores: 4
    runtime: 30
    slurm_partition: 30mins
  make_gembs_metadata:
    mem_mb: 4000
    threads: 4
    cores: 4
    runtime: 30
    slurm_partition: 30mins
  gembs_prepare:
    mem_mb: 4000
    threads: 4
    cores: 4
    runtime: 30
    slurm_partition: 30mins
  gembs_index:
    threads: 64
    cores: 64
    mem_mb: 96000
  parse_map_qc_html:
    mem_mb: 4000
    threads: 4
    cores: 4
    runtime: 30
    slurm_partition: 30mins
  gembs_map:
    threads: 88
    cores: 88
    mem_mb: 128000
    runtime: 7200
    slurm_partition: 5days

use-apptainer: True
apptainer-prefix: workflow/envs
software-deployment-method: "apptainer"
apptainer-args: "-B /zata,/data"

rerun-incomplete: True
printshellcmds: True
retries: 3

resources:
  mapping_jobs: 1