executor: slurm
jobs: 128

set-resources:
  indexing:
    runtime: 720
    slurm_partition: 12hours
  mapping:
    runtime: 7200
    slurm_partition: 5days
  generate_chrome_ctgs:
    runtime: 30
    slurm_partition: 30mins
  calling:
    runtime: 240
    slurm_partition: 4hours
  merge_chroms:
    runtime: 240
    slurm_partition: 4hours
  gembs_extract:
    runtime: 720
    slurm_partition: 12hours
  make_bedmethyl_pearson_correlation:
    runtime: 30
    slurm_partition: 30mins

use-apptainer: True
apptainer-prefix: workflow/rules/envs
software-deployment-method: apptainer
apptainer-args: -B /zata,/data

use-conda: True
conda-prefix: workflow/rules/envs
software-deployment-method: conda

rerun-incomplete: True
printshellcmds: True
# retries: 1

resources:
  mapping_jobs: 1
  calling_jobs: 12